# Generated by Django 5.0.4 on 2024-06-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='imagem_curso',
        ),
    ]
