# Generated by Django 5.0.4 on 2024-06-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0002_remove_alunos_funcionario_remove_cursos_imagem_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='curso',
        ),
        migrations.AddField(
            model_name='alunos',
            name='idade_aluno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
