# Generated by Django 5.0.6 on 2024-07-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0003_remove_alunos_curso_alunos_idade_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='data_de_inicio',
            field=models.DateField(),
        ),
    ]
